server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8008}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: user-service
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      file: docker-compose-dev.yaml

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

storage:
  s3:
    endpoint: https://storage.yandexcloud.net/
    region: ru-central1
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: hbs-bucket
    path:
      delim: /
    url-expiration-seconds: 900