-- liquibase formatted sql

-- changeset kanaoki:1749929874667-1
CREATE TABLE avatar (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, s3key VARCHAR(255) NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT pk_avatar PRIMARY KEY (id));

-- changeset kanaoki:1749929874667-2
CREATE TABLE interest (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, CONSTRAINT pk_interest PRIMARY KEY (id));

-- changeset kanaoki:1749929874667-3
CREATE TABLE preference (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, language VARCHAR(255) NOT NULL, timezone VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, notification VARCHAR(255), CONSTRAINT pk_preference PRIMARY KEY (id));

-- changeset kanaoki:1749929874667-4
CREATE TABLE user_interests (interest_id BIGINT NOT NULL, user_id UUID NOT NULL, CONSTRAINT pk_user_interests PRIMARY KEY (interest_id, user_id));

-- changeset kanaoki:1749929874667-5
CREATE TABLE users (id UUID NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, phone_number VARCHAR(20), role VARCHAR(255) NOT NULL, avatar_id BIGINT, preference_id BIGINT NOT NULL, is_deleted BOOLEAN, deleted_at TIMESTAMP WITHOUT TIME ZONE, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT pk_users PRIMARY KEY (id));

-- changeset kanaoki:1749929874667-6
ALTER TABLE avatar ADD CONSTRAINT uc_avatar_s3key UNIQUE (s3key);

-- changeset kanaoki:1749929874667-7
ALTER TABLE interest ADD CONSTRAINT uc_interest_name UNIQUE (name);

-- changeset kanaoki:1749929874667-8
ALTER TABLE users ADD CONSTRAINT uc_users_avatar UNIQUE (avatar_id);

-- changeset kanaoki:1749929874667-9
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset kanaoki:1749929874667-10
ALTER TABLE users ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

-- changeset kanaoki:1749929874667-11
ALTER TABLE users ADD CONSTRAINT uc_users_preference UNIQUE (preference_id);

-- changeset kanaoki:1749929874667-12
ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_AVATAR FOREIGN KEY (avatar_id) REFERENCES avatar (id);

-- changeset kanaoki:1749929874667-13
ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_PREFERENCE FOREIGN KEY (preference_id) REFERENCES preference (id);

-- changeset kanaoki:1749929874667-14
ALTER TABLE user_interests ADD CONSTRAINT fk_useint_on_interest FOREIGN KEY (interest_id) REFERENCES interest (id);

-- changeset kanaoki:1749929874667-15
ALTER TABLE user_interests ADD CONSTRAINT fk_useint_on_user FOREIGN KEY (user_id) REFERENCES users (id);

